version: "3.9"

services:
  sqlite:
    image: ghcr.io/tursodatabase/libsql-server:latest
    volumes:
      - ./data:/var/lib/sqld
    environment:
      - SQLD_NODE=primary
    ports:
      - "6001:8080"

