import { createElementId } from "./elements";
import type { OGElement } from "./types";

export interface Template {
  name: string;
  description: string;
  elements: OGElement[];
}

/**
 * The list of all available templates. Each template is composed of an array of
 * elements, a name and a description.
 */
export const TEMPLATES = [
  {
    name: "Default",
    description:
      "A simple Open Graph image composed of a title and a subtitle, with a subtle blue gradient.",
    elements: [
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        x: 0,
        y: 0,
        width: 1200,
        height: 630,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#ffffff",
        gradient: {
          start: "#595cff",
          end: "#c6f8ff",
          angle: 195,
          type: "linear",
        },
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        x: 95,
        y: 278,
        width: 643,
        height: 131,
        visible: true,
        rotate: 0,
        opacity: 100,
        content: "OG Studio",
        color: "#0d0f45",
        fontFamily: "Montserrat",
        fontWeight: 600,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 120,
        align: "left",
      },
      {
        tag: "p",
        id: "5dwujy4uo",
        name: "Text",
        x: 95,
        y: 415,
        width: 597,
        height: 138,
        visible: true,
        rotate: 0,
        opacity: 70,
        content: "Image builder",
        color: "#0d0f45",
        fontFamily: "Montserrat",
        fontWeight: 600,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 80,
        align: "left",
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        x: 941,
        y: -163,
        width: 432,
        height: 432,
        visible: true,
        rotate: 0,
        opacity: 10,
        backgroundColor: "#000000",
        radius: 999,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        x: 1005,
        y: -95,
        width: 300,
        height: 300,
        visible: true,
        rotate: 0,
        opacity: 10,
        backgroundColor: "#000000",
        radius: 999,
      },
    ],
  },
  {
    name: "Space",
    description:
      'A deep-purple Open Graph image with a "space" vibe, composed of a title and a subtitle.',
    elements: [
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        x: 0,
        y: 0,
        width: 1200,
        height: 630,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#ffffff",
        gradient: {
          start: "#07000a",
          end: "#3a023b",
          angle: 0,
          type: "linear",
        },
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 675,
        height: 675,
        visible: true,
        rotate: 0,
        opacity: 10,
        backgroundColor: "#c259f3",
        radius: 999,
        x: -329,
        y: 183,
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        width: 1183,
        height: 182,
        visible: true,
        rotate: 0,
        opacity: 100,
        content: "A Title.",
        color: "#c259f3",
        fontFamily: "Poppins",
        fontWeight: 600,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 200,
        align: "center",
        x: 9,
        y: 214,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 675,
        height: 675,
        visible: true,
        rotate: 0,
        opacity: 10,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 732,
        y: -237,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 101,
        y: 56,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 635,
        y: 80,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 230,
        y: 555,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 615,
        y: 444,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 976,
        y: 595,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 1105,
        y: 237,
      },
      {
        tag: "div",
        id: "z61mzs97b",
        name: "Rounded box",
        width: 15,
        height: 15,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 915,
        y: 169,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 15,
        height: 15,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 220,
        y: 188,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 15,
        height: 15,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 53,
        y: 490,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 15,
        height: 15,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 1141,
        y: 502,
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        width: 454,
        height: 62,
        visible: true,
        rotate: 0,
        opacity: 100,
        content: "And a subtitle.",
        color: "#d7d5d8",
        fontFamily: "Poppins",
        fontWeight: 600,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 60,
        align: "left",
        x: 269,
        y: 410,
      },
    ],
  },
  {
    name: "Blog post",
    description:
      "Perfect for blog posts, this Open Graph image has an illustration and displays the title and author name.",
    elements: [
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        x: 0,
        y: 0,
        width: 1200,
        height: 630,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#1f1f1f",
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Image",
        width: 958,
        height: 687,
        visible: true,
        rotate: -2,
        opacity: 100,
        backgroundColor: "#000000",
        backgroundImage:
          "https://images.unsplash.com/reserve/bOvf94dPRxWu0u3QsPjF_tree.jpg?q=80&w=2976&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        backgroundSize: "cover",
        x: 668,
        y: -35,
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        width: 1037,
        height: 85,
        visible: true,
        rotate: 0,
        opacity: 100,
        content: "Blog post title",
        color: "#ffffff",
        fontFamily: "Inter",
        fontWeight: 600,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 80,
        align: "left",
        x: 59,
        y: 475,
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        width: 1035,
        height: 31,
        visible: true,
        rotate: 0,
        opacity: 100,
        content: "Author name",
        color: "#d6d6d6",
        fontFamily: "Inter",
        fontWeight: 400,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 30,
        align: "left",
        x: 61,
        y: 416,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 224,
        height: 2,
        visible: true,
        rotate: 0,
        opacity: 100,
        backgroundColor: "#7ba71d",
        x: 60,
        y: 460,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 2,
        height: 700,
        visible: true,
        rotate: -2,
        opacity: 100,
        backgroundColor: "#7ba71d",
        x: 665,
        y: -34,
      },
    ],
  },
] satisfies Template[];
