import { createElementId } from "./elements";
import type { OGElement } from "./types";

export interface Template {
  name: string;
  description: string;
  elements: OGElement[];
}

/**
 * Returns the slug of a template to be used in URLs. It returns the name of the
 * template in lowercase and with spaces replaced by dashes.
 */
export function toTemplateSlug(template: Template): string {
  return template.name.toLowerCase().replaceAll(" ", "-");
}

/**
 * The list of all available templates. Each template is composed of an array of
 * elements, a name and a description.
 */
export const TEMPLATES = [
  {
    name: "Default",
    description:
      "A simple Open Graph image composed of a title and a subtitle, with a subtle blue gradient.",
    elements: [
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        x: 0,
        y: 0,
        width: 1200,
        height: 630,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#ffffff",
        gradient: {
          start: "#595cff",
          end: "#c6f8ff",
          angle: 195,
          type: "linear",
        },
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        x: 95,
        y: 278,
        width: 643,
        height: 131,
        visible: true,
        rotate: 0,
        blur: 0,
        content: "OG Studio",
        color: "#0d0f45",
        fontFamily: "Montserrat",
        fontWeight: 600,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 120,
        align: "left",
      },
      {
        tag: "p",
        id: "5dwujy4uo",
        name: "Text",
        x: 95,
        y: 415,
        width: 597,
        height: 138,
        visible: true,
        rotate: 0,
        blur: 0,
        content: "Image builder",
        color: "#0d0f45a8",
        fontFamily: "Montserrat",
        fontWeight: 600,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 80,
        align: "left",
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        x: 941,
        y: -163,
        width: 432,
        height: 432,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#00000019",
        radius: 999,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        x: 1005,
        y: -95,
        width: 300,
        height: 300,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#00000019",
        radius: 999,
      },
    ],
  },
  {
    name: "AI Startup",
    description:
      "A futuristic Open Graph image with a dark background and subtle colors.",
    elements: [
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 1200,
        height: 630,
        visible: true,
        rotate: 0,
        backgroundColor: "#050d26",
        x: 0,
        y: 0,
        blur: 0,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 569,
        height: 502,
        visible: true,
        rotate: 0,
        backgroundColor: "#0c3df040",
        radius: 999,
        x: -149,
        y: 348,
        blur: 100,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 569,
        height: 502,
        visible: true,
        rotate: 0,
        backgroundColor: "#0cf0e940",
        radius: 999,
        x: 994,
        y: 297,
        blur: 100,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 569,
        height: 502,
        visible: true,
        rotate: 0,
        backgroundColor: "#f00cd140",
        radius: 999,
        x: 538,
        y: -388,
        blur: 100,
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        width: 1161,
        height: 186,
        visible: true,
        rotate: 0,
        content: "AI startup",
        color: "#ffffff",
        fontFamily: "Raleway",
        fontWeight: 400,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 140,
        align: "center",
        x: 13,
        y: 220,
        blur: 0,
      },
    ],
  },
  {
    name: "Space",
    description:
      'A deep-purple Open Graph image with a "space" vibe, composed of a title and a subtitle.',
    elements: [
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        x: 0,
        y: 0,
        width: 1200,
        height: 630,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#ffffff",
        gradient: {
          start: "#07000a",
          end: "#3a023b",
          angle: 0,
          type: "linear",
        },
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 675,
        height: 675,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f319",
        radius: 999,
        x: -329,
        y: 183,
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        width: 1183,
        height: 182,
        visible: true,
        rotate: 0,
        blur: 0,
        content: "A Title.",
        color: "#c259f3",
        fontFamily: "Poppins",
        fontWeight: 600,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 200,
        align: "center",
        x: 9,
        y: 214,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 675,
        height: 675,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f319",
        radius: 999,
        x: 732,
        y: -237,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 101,
        y: 56,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 635,
        y: 80,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 230,
        y: 555,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 615,
        y: 444,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 976,
        y: 595,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 5,
        height: 5,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 1105,
        y: 237,
      },
      {
        tag: "div",
        id: "z61mzs97b",
        name: "Rounded box",
        width: 15,
        height: 15,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 915,
        y: 169,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 15,
        height: 15,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 220,
        y: 188,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 15,
        height: 15,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 53,
        y: 490,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Rounded box",
        width: 15,
        height: 15,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#c259f3",
        radius: 999,
        x: 1141,
        y: 502,
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        width: 454,
        height: 62,
        visible: true,
        rotate: 0,
        blur: 0,
        content: "And a subtitle.",
        color: "#d7d5d8",
        fontFamily: "Poppins",
        fontWeight: 600,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 60,
        align: "left",
        x: 269,
        y: 410,
      },
    ],
  },
  {
    name: "Blog post",
    description:
      "Perfect for blog posts, this Open Graph image has an illustration and displays the title and author name.",
    elements: [
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        x: 0,
        y: 0,
        width: 1200,
        height: 630,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#1f1f1f",
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Image",
        width: 958,
        height: 687,
        visible: true,
        rotate: -2,
        blur: 0,
        backgroundColor: "#000000",
        backgroundImage:
          "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1280&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        backgroundSize: "cover",
        x: 668,
        y: -35,
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        width: 1037,
        height: 85,
        visible: true,
        rotate: 0,
        blur: 0,
        content: "Blog post title",
        color: "#ffffff",
        fontFamily: "Inter",
        fontWeight: 600,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 80,
        align: "left",
        x: 59,
        y: 455,
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        width: 1035,
        height: 31,
        visible: true,
        rotate: 0,
        blur: 0,
        content: "Author name",
        color: "#d6d6d6",
        fontFamily: "Inter",
        fontWeight: 400,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 30,
        align: "left",
        x: 61,
        y: 396,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 224,
        height: 3,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#aad749",
        x: 61,
        y: 438,
        radius: 2,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 3,
        height: 700,
        visible: true,
        rotate: -2,
        blur: 0,
        backgroundColor: "#aad749",
        x: 665,
        y: -34,
      },
    ],
  },
  {
    name: "Technical blog post",
    description:
      "An abstract Open Graph image that is perfect for technical blog posts, composed of a title and an author name.",
    elements: [
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        x: 0,
        y: 0,
        width: 1200,
        height: 630,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#ffffff",
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 100,
        height: 100,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#00000000",
        x: 1,
        y: 1,
        border: { color: "#adadad", width: 1, style: "outside" },
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 100,
        height: 100,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#00000000",
        x: 102,
        y: 102,
        border: { color: "#adadad", width: 1, style: "outside" },
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 100,
        height: 100,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#00000000",
        x: 203,
        y: 203,
        border: { color: "#adadad", width: 1, style: "outside" },
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 100,
        height: 100,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#1586ff",
        x: 304,
        y: 304,
        border: { color: "#1586ff", width: 1, style: "outside" },
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 100,
        height: 100,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#00000000",
        x: 405,
        y: 405,
        border: { color: "#adadad", width: 1, style: "outside" },
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 100,
        height: 100,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#00000000",
        x: 506,
        y: 506,
        border: { color: "#adadad", width: 1, style: "outside" },
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 100,
        height: 100,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#00000000",
        x: 607,
        y: 607,
        border: { color: "#adadad", width: 1, style: "outside" },
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 100,
        height: 100,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#00000000",
        x: 102,
        y: 506,
        border: { color: "#adadad", width: 1, style: "outside" },
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 100,
        height: 100,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#00000000",
        x: 506,
        y: 102,
        border: { color: "#adadad", width: 1, style: "outside" },
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        width: 764,
        height: 97,
        visible: true,
        rotate: 0,
        blur: 0,
        content: "Blog post title",
        color: "#1486ff",
        fontFamily: "Montserrat",
        fontWeight: 500,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 100,
        align: "right",
        x: 408,
        y: 145,
      },
      {
        tag: "div",
        id: createElementId(),
        name: "Box",
        width: 100,
        height: 100,
        visible: true,
        rotate: 0,
        blur: 0,
        backgroundColor: "#00000000",
        x: 809,
        y: 405,
        border: { color: "#adadad", width: 1, style: "outside" },
      },
      {
        tag: "p",
        id: createElementId(),
        name: "Text",
        width: 403,
        height: 48,
        visible: true,
        rotate: 0,
        blur: 0,
        content: "Author name",
        color: "#0759b0",
        fontFamily: "Montserrat",
        fontWeight: 400,
        lineHeight: 1,
        letterSpacing: 0,
        fontSize: 40,
        align: "right",
        x: 768,
        y: 557,
      },
    ],
  },
] as const satisfies Template[];
